### ISSUE TITLE
Hello, some problem in stationName

### ISSUE THREAD

**Issue by Shaw2** [gpailler/MMM-aqicn#3]
Hello, first of all, thank you for your effort to make this.

Unfortunately, I have a problem in it.

I live nearby Myeongnyun-dong, Wonju-si, Gangwon, South Korea.
So I chose that station but it didn't work. I tried other even though your example "Bangkok University Rangsit Campus, Pathum Thani" but it also didn't work. 

I thought my token should be wrong, however it wasn't.
Fortunately, I found a station that works. It was Seoul. So I tried 'Gangwon / Wonju-si / Wonju-si, Gangwon'. But as u can imagine, it didn't work...

Could you tell me the solution?

Thanks :)

**Comment by gpailler** [comment]
To ensure your token is valid, could you visit http://aqicn.org/json-api/demo/, and enter your token and your city.

**Comment by Shaw2** [comment]
Hello :)

I should have written that it wasn't displayed on screen.
I can see information of "Bangkok University Rangsit Campus, Pathum Thani", 'Gangwon / Wonju-si / Wonju-si, Gangwon' and so on. 

But only Seoul was displayed on screen. That was the point of my question.

Do you know about this kind of problem?

**Comment by gpailler** [comment]
Sorry, I don't get it. With the following configuration, the information is properly displayed on my side
```
{
    module: "MMM-aqicn",
    position: "top_left",
    header: "AQICN",
    config: {
        token: "[TOKEN]",
        stationName: "Myeongnyun-dong, Wonju-si, Gangwon, South Korea",
        showLocationName: false,
        showDetails: true
    }
},
```

Could you share your config and/or a screenshot when something is displayed or not

**Comment by Shaw2** [comment]
Hi, I'm really sorry about too late reply.

I think the problem was in my raspberry pi 3. Because it doesn't work 'openweathermap' and even 'google calendar'. I think the problem is my rpi3 is not on network when it launch the 'MagicMirror'. 
I mean rpi3 is connected with Wifi (It works!), but the network connection is not worked in 'MagicMirror'. 

For example, openweathermap also doesn't work 'UNDEFINED WONJU, KR' 

Here is the config.js & screen image.
If you get any idea about this problem, please tell me.


```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
  address: "localhost",
  port: 8080,
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],
  language: "ko",
  timeFormat: 12,
  units: "metric",

  modules: [
    {
      module: "alert",
    },
    {
      module: "updatenotification",
      position: "top_bar"
    },
    {
      module: "clock",
      position: "top_left",
      config: {
        dateFormat: "LL dddd",
      }
    },
    {
      module: "calendar",
      position: "top_left",
      config: {
        urgency: 21,
        fetchInterval: 3600000,
        calendars: [{
          url: 'https://calendar.google.com/calendar/ical/*******%40gmail.com/public/basic.ics',
          symbol: 'My Calendar',
        }, ]
      }
    },
    {
      module: "currentweather",
      position: "top_right",
      config: {
        location: "Wonju, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.
        locationID: "1833105",
        appid: "3363751********0ea3" //openweathermap.org의 API key를 입력하세요.
      }
    },
    {
      module: "weatherforecast",
      position: "top_right",
      config: {
        location: "Wonju, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.
        locationID: "1833105",
        appid: "3363751*******0ea3" //openweathermap.org의 API key를 입력하세요.
      }
    },
    {
      module: "compliments",
      position: "lower_third",
      config: {
        compliments: {
          anytime: [ //아무때나
            "오늘도 좋은 하루!"
          ],
          morning: [ //아침
            "좋은 아침!",
            "힘찬 아침!",
            "잘 잤나요?"
          ],
          afternoon: [ //오후
            "안녕하세요!",
            "멋져요!",
            "잘 지내고 있나요!"
          ],
          evening: [ //저녁
            "와우! 잘 지냈나요?",
            "멋져보이네요!",
            "반가워요!"
          ],
          day_sunny: [//맑은 낮
            
          ],
          day_cloudy: [//흐린 낮
            
          ],
          cloudy: [//흐림

          ],
          cloudy_windy: [//흐리고 바람

          ],
          showers: [//소나기

          ],
          rain: [//비

          ],
          thunderstorm: [//천둥번개

          ],
          snow: [//눈

          ],
          fog: [//안개

          ],
          night_clear: [//맑은 밤

          ],
          night_cloudy: [//흐린 밤

          ],
          night_showers: [//소나기 밤

          ],
          night_rain: [//비오는 밤

          ],
          night_thunderstorm: [//천둥번개 밤

          ],
          night_snow: [//눈오는 밤

          ],
          night_alt_cloudy_windy: [//흐리고 바람부는 밤

          ],
        }
      }
    },
    {
      module: "MMM-AssistantMk2",
      position: "top_right",
      config: {
        record: {
          recordProgram : "arecord",  
          device        : "plughw:1",
        },
        notifications: {
          ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
          ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
        },
        deviceLocation: {
          coordinates: {
            latitude: 37.57,
            longitude: 126.98
          }
        },
        profiles: {
          "default": {
           lang: "ko-KR"
          }
        }
      }
    },
    {
      module: "MMM-Hotword",
      config: {
        snowboy: [
          {
            hotwords: "smartmirror",
            file: "resources/models/smart_mirror.umdl",
            sensitivity: '1.0',
          },
          {
            hotwords: "snowboy",
            file: "resources/models/snowboy.umdl",
            sensitivity: '1.0',
          },
          {
            file: 'resources/models/jarvis.umdl',
            sensitivity: '0.8,0.80',
            hotwords: ['jarvis', 'jarvis']
          }
        ],
        record: {
          recordProgram : "arecord",  
          device        : "plughw:1",
        },
        autostart:true,
        onDetected: {
          notification: function (payload) {
            return "ASSISTANT_ACTIVATE"
          },
          payload: function (payload){
            return {
              profile: payload.hotword
            }
          }
        },
      },
    },
  ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {
  module.exports = config;
}
```

![SmartMirror](https://user-images.githubusercontent.com/49862639/68361051-b0566c80-0165-11ea-9a50-72e422daba38.png)

**Comment by gpailler** [comment]
I have no idea about this 'undefined' issue. Maybe you can try to display the developer tools by pressing CTRL-SHIFT-i and check if there is any helpful error in the console.

**Comment by Shaw2** [comment]
Thank u :)

**Comment by Shaw2** [comment]
Hi gpailler :) 
I solved previous problem. Maybe it wasn't a big deal.

So.. I reinstalled MMM-aqicn. but it's not worked. As u mentioned, it can be a token problem. 
So I got 2 tokens by 2 e-mails but it didn't work. 

I tried many cities, however I got same answer "MMM-aqicn Station name "[station]" not found"

"Seoul" / "Myeongnyun-dong, Wonju-si, Gangwon" / "Bangkok University Rangsit Campus, Pathum Thani" / "Bangkok University Rangsit Campus, Pathum Thani, Thailand" / "Bodindecha Sing Singhaseni School, Bangkok"


![image](https://user-images.githubusercontent.com/49862639/69925287-b801fa80-14f2-11ea-9ad2-bbf29cdd9103.png)

![image](https://user-images.githubusercontent.com/49862639/69925291-bd5f4500-14f2-11ea-930a-5d0a05f90551.png)

**Comment by Janachi** [comment]
안녕하세요?! 한국분인거 같아서 한글로 답변을 달아요
저도 이 3rd party module 사용해볼려고 했는데 작성자님 과 같은 현상이 발생이 되더라구요
일단
1. stationName에 공백이 없어야 해당 지역을 찾을 수 있었습니다.
2. stationName에 공백을 지우고 하더라도 검증 단계에서 일치하지 않아 uid를 찾을 수 없습니다.

그래서
1. config.js에는 
   http://aqicn.org/json-api/demo/ 에서 해당 지역을 찾아 Search Result에서 원하는 지역을 텍스트를 복사하시고, stationName에 붙여 주세요
원하는 지역은 해당 칸의 세미콜론 뒤에 다 복사했어요
![image](https://user-images.githubusercontent.com/34957821/78634946-0fb8d400-78e0-11ea-81ed-a2ece5612b6d.png)

![image](https://user-images.githubusercontent.com/34957821/78634889-f0ba4200-78df-11ea-9053-103178e3c152.png)
2. MMM-aqicn.js파일에서 좀 수정이 되어야 하는데
조금만 내려보시면
initialize: function(){ 아래쪽
token과 keyword가 보입니다.
keyword: this.config.stationName 부분 뒤에
.replace(/(\s*)/g,"")
를 추가해주세요. 그리고 좀 더 아래
if (x.station.name == self.config.stationName) {
부분은 주석(//)을 해주시고 바로 아래에
if (x.station.name.indexOf(self.config.stationName) != -1) {
을 삽입해주세요
if문 위에 forEach를 every로 바꾸시고
self.data.stationId = x.uid;   바로 아래에
return false;  를 넣어주세요
![image](https://user-images.githubusercontent.com/34957821/78668247-4eb54c80-7915-11ea-829c-b6b1cf7fb995.png)

그런 다음 다시 매직미러를 실행해보시면 될 것 같습니다.

**Comment by Shaw2** [comment]
오 답변 감사드립니다. 제가 답이 너무 늦었네요.

지금 포맷을 한 상태여서 적용은 못해봤는데 적용하면 바로 알려드리겠습니다.

감사합니다 :)
