### ISSUE TITLE
Bad coding

### ISSUE THREAD

**Issue by ghost** [gpailler/MMM-aqicn#7]
Very bad coding module, lazy work

**Comment by gpailler** [comment]
Hi Razvan

I'm willing to improve this module if you can give me more specific details in a more helpful feedback.

Thanks

**Comment by ghost** [comment]
get rid of jquery and make stationname more easy to set like using default location from config.js
arrow function do not work on old ipad with safari 9, incompatible with ES6

**Comment by gpailler** [comment]
Thanks for your feedback. Do you have time to help on this project (for the iPad part for example) and send a Pull Request?

**Comment by hangorazvan** [comment]
instead of
`response.data.forEach(x => {`
make
`response.data.forEach(function (x) {`
