### ISSUE TITLE
feature request: more stations support

### ISSUE THREAD

**Issue by umbynos** [gpailler/MMM-aqicn#8]
Hello! Nice module!
I was wondering if it would be easy to implement also stations like this one (https://aqicn.org/station/@58333)
It does not seems to be working with that kind of stations

**Comment by gpailler** [comment]
Hi,

I checked on https://aqicn.org/json-api/demo/ and I don't see how we can retrieve this kind of station. Do you know why this specific station is identified with @58333 in the url?

![image](https://user-images.githubusercontent.com/3621529/99968713-75f15900-2dd4-11eb-8e07-decb52c0a487.png)

**Comment by umbynos** [comment]
Unfortunately, I have no idea. After a bit of research I discovered that probably it's because it's from another service:
If I try to open that station for more information it says: "Station [9942] from Citizen Science project luftdaten.info - https://luftdaten.info".

If I try to open this one instead (https://aqicn.org/station/italy/piemonte/torino/rubino) for example is says something different: "Station provided by ARAP Piemonte - Agenzia Regionale per la Protezione dell'aria in Piemonte) - http://www.sistemapiemonte.it/ambiente/srqa/"

I do not have a problem using the second one instead, but the station seems to be always offline...

**Comment by gpailler** [comment]
Ok thanks for the investigation.
Unfortunately, if the station is not exposed by the AQICN API, there is not much to do...

**Comment by umbynos** [comment]
Ok, thank you :cry:
